name: 'Arturo action'
description: 'Setup Arturo environment'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@main
      with:
        repository: arturo-lang/arturo
        submodules: recursive

    - run: |
        wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
        echo "$HOME/.nimble/bin" >> $GITHUB_PATH

    - if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-dev
        
    - run: |
        nim --version
        
    - run: |
        ./install ${{ matrix.version }} log
        echo "$HOME/.arturo/bin" >> $GITHUB_PATH