name: 'Arturo action'
description: 'Setup Arturo environment'
icon: at-sign
color: purple
runs:
  using: "composite"
  steps:
    - run: |
        git clone https://github.com/arturo-lang/arturo.git
      shell: bash
    
    - if: runner.os == 'Linux':
      run: |
        echo "we are on Linux"

    - if: runner.os == 'Windows':
      run: |
        echo "we are on Windows"

    - if: runner.os == 'macOS':
      run: |
        echo "we are on macOS"

    - run: |
        export CHOOSENIM_CHOOSE_VERSION=2.0.4
        wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
        echo "$HOME/.nimble/bin" >> $GITHUB_PATH
        export PATH=/home/runner/.nimble/bin:$PATH
        nim --version
      shell: bash

    - run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-dev libmpfr-dev
      shell: bash
        
    - run: |
        cd arturo
        ./build.nims --install --log
        echo "$HOME/.arturo/bin" >> $GITHUB_PATH
        cd ..
      shell: bash