name: 'Arturo action'
description: 'Setup Arturo environment'
inputs:
    mode:
        description: >-
            The Arturo version to install
            (one of 'mini', 'full', 'web')
        default: 'full'
    token:
        description: >-
            The GITHUB_TOKEN secret.
        required: true
runs:
    using: "composite"
    steps:
        - name: Clone Arturo repository
          run: |
            git clone https://github.com/arturo-lang/arturo.git
          shell: bash

        - name: Install Nim
          uses: jiro4989/setup-nim-action@v1
          with:
            nim-version: '2.0.4'
            repo-token: ${{ inputs.token }}

        - name: Install dependencies (mini / x86)
          if: runner.os == 'Linux' && inputs.mode == 'mini' && runner.arch != 'ARM' && runner.arch != 'ARM64'
          run: |
            sudo apt-get update
            sudo apt-get install gcc-multilib g++-multilib
          shell: bash

        - name: Install dependencies (mini / arm)
          if: runner.os == 'Linux' && inputs.mode == 'mini' && (runner.arch == 'ARM' || runner.arch == 'ARM64')
          run: |
            sudo apt-get update
            sudo apt-get install gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
          shell: bash

        - name: Install dependencies (full)
          if: runner.os == 'Linux' && inputs.mode != 'mini'
          run: |
            sudo apt-get update
            sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev libmpfr-dev
          shell: bash
        
        - name: Compile Arturo
          run: |
            cd arturo
            ./build.nims --install --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

branding:
    icon: terminal
    color: purple