name: 'Arturo Builder'
description: 'Setup Arturo environment'
branding:
    icon: terminal
    color: purple
inputs:
    mode:
        description: >-
            The Arturo version to install
            (one of: 'mini', 'full', 'docgen', 'safe')
        default: 'full'
    token:
        description: >-
            The GITHUB_TOKEN secret.
        required: true
    arch:
        description: >-
            The architecture to build for.
            (one of: 'amd64', 'arm64')
        default: 'amd64'
    src:
        description: >-
            Which Arturo version to use.
        default: ''
    metadata:
        description: >-
            Embeddable build metadata
        default: ''
    os:
        description: >-
            Target operating system
            (one of: 'linux', 'windows', 'macos', 'freebsd', 'web')
        default: 'linux'
    webkit:
        description: >-
            WebKit version for Linux/FreeBSD full builds (one of: '40', '41')
        default: '41'
runs:
    using: "composite"
    steps:
        - name: Sanitize inputs and auto-detect platform
          id: v
          run: |
            # Auto-detect OS if not specified or is default 'linux'
            if [ "${{ inputs.os }}" = "" ] || [ "${{ inputs.os }}" = "linux" ]; then
                case "${{ runner.os }}" in
                    Linux)   detected_os="linux" ;;
                    macOS)   detected_os="macos" ;;
                    Windows) detected_os="windows" ;;
                    *)       detected_os="linux" ;;
                esac
            else
                detected_os="${{ inputs.os }}"
            fi

            # Auto-detect arch if not specified or is default 'amd64'
            if [ "${{ inputs.arch }}" = "" ] || [ "${{ inputs.arch }}" = "amd64" ]; then
                case "${{ runner.arch }}" in
                    ARM64) detected_arch="arm64" ;;
                    X64)   detected_arch="amd64" ;;
                    *)     detected_arch="amd64" ;;
                esac
            else
                detected_arch="${{ inputs.arch }}"
            fi

            # Auto-detect webkit version based on Ubuntu version if not specified
            if [ "${{ inputs.webkit }}" = "" ] || [ "${{ inputs.webkit }}" = "41" ]; then
                if [ "${{ runner.os }}" = "Linux" ]; then
                    UBUNTU_VERSION=$(lsb_release -rs 2>/dev/null || echo "24.04")
                    if [[ "$UBUNTU_VERSION" < "24.04" ]]; then
                        detected_webkit="40"
                    else
                        detected_webkit="41"
                    fi
                else
                    detected_webkit="41"
                fi
            else
                detected_webkit="${{ inputs.webkit }}"
            fi

            # Set mode to 'web' if os is 'web', otherwise use input
            if [ "$detected_os" = "web" ]; then
                detected_mode="web"
            else
                detected_mode="${{ inputs.mode != '' && inputs.mode || 'full' }}"
            fi

            echo "os=$detected_os" >> $GITHUB_OUTPUT
            echo "arch=$detected_arch" >> $GITHUB_OUTPUT
            echo "mode=$detected_mode" >> $GITHUB_OUTPUT
            echo "webkit=$detected_webkit" >> $GITHUB_OUTPUT
            echo "src=${{ inputs.src }}" >> $GITHUB_OUTPUT
            echo "metadata=${{ inputs.metadata }}" >> $GITHUB_OUTPUT
          shell: bash

        - name: Set environment variables
          run: |
            echo "os=${{ steps.v.outputs.os }}" >> $GITHUB_ENV
            echo "arch=${{ steps.v.outputs.arch }}" >> $GITHUB_ENV
            echo "mode=${{ steps.v.outputs.mode }}" >> $GITHUB_ENV
            echo "webkit=${{ steps.v.outputs.webkit }}" >> $GITHUB_ENV
            echo "src=${{ steps.v.outputs.src }}" >> $GITHUB_ENV
            echo "metadata=${{ steps.v.outputs.metadata }}" >> $GITHUB_ENV
          shell: bash

        - name: Debug build configuration
          run: |
            echo "======================================"
            echo "Arturo Builder Configuration"
            echo "======================================"
            echo "Runner OS:        ${{ runner.os }}"
            echo "Runner Arch:      ${{ runner.arch }}"
            echo "======================================"
            echo "Target OS:        ${{ env.os }}"
            echo "Target Arch:      ${{ env.arch }}"
            echo "Build Mode:       ${{ env.mode }}"
            echo "WebKit Version:   ${{ env.webkit }}"
            echo "Source Ref:       ${{ env.src != '' && env.src || '(latest)' }}"
            echo "Metadata:         ${{ env.metadata != '' && env.metadata || '(none)' }}"
            echo "======================================"
          shell: bash

        - name: Checkout Arturo repo
          if: env.os != 'freebsd'
          uses: actions/checkout@v4
          with:
            repository: arturo-lang/arturo
            submodules: recursive
            path: arturo
            ref: ${{ env.src }}

        - name: Set build metadata
          if: env.os != 'freebsd' && env.metadata != ''
          run: |
            echo "${{ env.metadata }}" > arturo/version/metadata
          shell: bash

        - name: Cache ChooseNim
          if: runner.os == 'Linux' || runner.os == 'macOS'
          id: cache-choosenim
          uses: actions/cache@v4
          with:
            path: ~/.choosenim
            key: ${{ runner.os }}-choosenim-${{ steps.get-date.outputs.date }}
  
        - name: Cache Nimble
          if: runner.os == 'Linux' || runner.os == 'macOS'
          id: cache-nimble
          uses: actions/cache@v4
          with:
            path: ~/.nimble
            key: ${{ runner.os }}-nimble-v2-${{ hashFiles('*.nimble') }}

        - name: Setup Msys
          if: runner.os == 'Windows'
          uses: msys2/setup-msys2@v2
          with:
            update: true
            cache: true
            install: 'git base-devel p7zip mingw-w64-x86_64-toolchain'

        - name: Install Nim (Linux)
          if: runner.os == 'Linux' && env.os != 'freebsd'
          uses: jiro4989/setup-nim-action@v2
          with:
            nim-version: '2.2.6'
            repo-token: ${{ inputs.token }}

        - name: Install Nim (macOS)
          if: runner.os == 'macOS'
          run: |
            brew update
            brew install pcre nim
          shell: bash

        - name: Install Nim (Windows)
          if: runner.os == 'Windows'
          run: |
            if [ "${{ env.mode }}" = "full" ]; then
              pacman --noconfirm -S mingw-w64-x86_64-mpfr
            fi

            mkdir dist
            mkdir nim
            curl -L https://nim-lang.org/download/dlls.zip -o dist/dlls.zip
            curl -L https://nim-lang.org/download/nim-2.2.6_x64.zip -o dist/nim.zip
            7z x dist/dlls.zip -obin
            7z x dist/nim.zip -onim

            export PATH="${{ github.workspace }}/nim/nim-2.2.6/bin":$PATH

            cd arturo
            ./build.nims build --mode ${{ env.mode }} --log
            cd ..
            cp bin/*.dll /usr/bin
            cp arturo/bin/arturo.exe /usr/bin

            if [ "${{ env.mode }}" = "full" ]; then
              curl -L https://arturo-lang.s3.amazonaws.com/extra-dlls.zip -o dist/extradlls.zip
              7z x dist/extradlls.zip -obin
              cp arturo/src/extras/webview/deps/dlls/x64/*.dll bin
              cp bin/*.dll /usr/bin
              curl -L https://curl.se/ca/cacert.pem -o /usr/bin/cacert.pem
            fi
          shell: msys2 {0}

        - name: Install dependencies (Linux)
          if: runner.os == 'Linux' && env.os != 'freebsd'
          run: |
            sudo apt-get update
            sudo apt-get install libpcre3
            
            if [ "${{ env.mode }}" != "mini" ]; then
              npm install -g uglify-js
              sudo apt-get install libgtk-3-dev libmpfr-dev
              UBUNTU_VERSION=$(lsb_release -rs)
              if [[ "$UBUNTU_VERSION" < "24.04" ]]; then
                  sudo apt-get install -y libwebkit2gtk-4.0-dev
              else
                  sudo apt-get install -y libwebkit2gtk-4.1-dev
              fi
            fi
          shell: bash
        
        - name: Compile Arturo (Linux/macOS - amd64)
          if: env.os != 'freebsd' && env.os != 'web' &&  runner.os != 'Windows' && env.arch == 'amd64' && runner.arch != 'ARM64'
          run: |
            cd arturo
            ./build.nims --install --mode ${{ env.mode }} --arch amd64 --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

        - name: Compile Arturo (macOS - M1)
          if: env.os != 'freebsd' && env.os != 'web' && env.arch == 'arm64' &&  (runner.os == 'macOS' && runner.arch == 'ARM64')
          run: |
            cd arturo
            ./build.nims --install --mode ${{ env.mode }} --arch arm64 --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

        - name: Compile Arturo (Linux)
          if: env.os != 'freebsd' && env.os != 'web' && env.arch != 'amd64' && runner.os == 'Linux'
          run: |
            cd arturo
            ./build.nims --install --mode ${{ env.mode }} --arch ${{ env.arch }} --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

        - name: Compile Arturo (Web)
          if: env.os == 'web'
          run: |
            cd arturo
            ./build.nims --mode web --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

        - name: Build Arturo (FreeBSD)
          if: env.os == 'freebsd'
          uses: vmactions/freebsd-vm@v1
          with:
            usesh: true
            sync: sshfs
            prepare: |
              pkg update
              pkg install -y wget nim bash git
              if [ "${{ env.mode }}" = "full" ]; then
                  pkg install -y pkgconf gtk3 mpfr openssl webkit2-gtk_${{ env.webkit }}
              fi
            run: |
              git clone --recursive https://github.com/arturo-lang/arturo.git arturo
              cd arturo
              git config --global --add safe.directory '*'
              ${{ env.src != '' && format('git checkout {0}', env.src) || '' }}
              ${{ env.metadata != '' && format('echo "{0}" > version/metadata', env.metadata) || '' }}
              export PATH="/usr/local/nim/bin/:$PATH"
              ./build.nims --install --mode ${{ env.mode }} --log