name: 'Arturo action'
description: 'Setup Arturo environment'
icon: at-sign
color: purple
runs:
  using: "composite"
  steps:
    - run: |
        git clone https://github.com/arturo-lang/arturo.git
      shell: bash
    
    - run: |
        wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
        echo "$HOME/.nimble/bin" >> $GITHUB_PATH
        export PATH=/home/runner/.nimble/bin:$PATH
        nim --version
      shell: bash

    - run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-dev
      shell: bash
        
    - run: |
        cd arturo
        ./build.nims install ${{ matrix.version }}
        echo "$HOME/.arturo/bin" >> $GITHUB_PATH
        cd ..
      shell: bash