name: 'Arturo Builder'
description: 'Setup Arturo environment'
branding:
    icon: terminal
    color: purple
inputs:
    mode:
        description: >-
            The Arturo version to install
            (one of: 'mini', 'full', 'docgen', 'safe')
        default: 'full'
    token:
        description: >-
            The GITHUB_TOKEN secret.
        required: true
    arch:
        description: >-
            The architecture to build for.
            (one of: 'x86', 'arm', 'arm64', 'amd64')
        default: 'amd64'
    src:
        description: >-
            Which Arturo version to use.
        default: ''
    metadata:
        description: >-
            Embeddable build metadata
        default: ''
    os:
        description: >-
            Target operating system
            (one of: 'linux', 'windows', 'macos', 'freebsd', 'web')
        default: 'linux'
    webkit:
        description: >-
            WebKit version for Linux/FreeBSD full builds (one of: '40', '41')
        default: '40'
runs:
    using: "composite"
    steps:
        - name: Resolve OS and Runner
          id: resolve
          run: |
            os="${{ inputs.os }}"
            arch="${{ inputs.arch }}"
            mode="${{ inputs.mode }}"
            webkit="${{ inputs.webkit }}"
            
            # Determine actual runner and shell based on simplified OS
            case "$os" in
              linux)
                if [ "$mode" = "full" ] && [ "$webkit" = "41" ]; then
                  runner="ubuntu-latest"
                else
                  runner="ubuntu-22.04"
                fi
                shell="bash"
                ;;
              windows)
                runner="windows-latest"
                shell="msys2 {0}"
                ;;
              macos)
                if [ "$arch" = "arm64" ]; then
                  runner="macos-latest"
                else
                  runner="macOS-15-intel"
                fi
                shell="bash"
                ;;
              freebsd|web)
                runner="ubuntu-latest"
                shell="bash"
                ;;
              *)
                echo "Unknown OS: $os"
                exit 1
                ;;
            esac
            
            echo "runner=$runner" >> $GITHUB_OUTPUT
            echo "shell=$shell" >> $GITHUB_OUTPUT
            echo "target_os=$os" >> $GITHUB_OUTPUT
          shell: bash

        - name: Checkout Arturo repo
          if: inputs.os != 'freebsd'
          uses: actions/checkout@v4
          with:
            repository: arturo-lang/arturo
            submodules: recursive
            path: arturo
            ref: ${{ inputs.src }}

        - name: Debugging
          if: inputs.os != 'freebsd'
          run: |
            echo ${{ runner.os }}
            echo ${{ runner.arch }}
            ls -la
            ls -la arturo
          shell: bash

        - name: Set build metadata
          if: inputs.os != 'freebsd' && inputs.metadata != ''
          run: |
            echo "${{ inputs.metadata }}" > arturo/version/metadata
          shell: bash

        - name: Cache ChooseNim
          if: runner.os == 'Linux' || runner.os == 'macOS'
          id: cache-choosenim
          uses: actions/cache@v4
          with:
            path: ~/.choosenim
            key: ${{ runner.os }}-choosenim-${{ steps.get-date.outputs.date }}
  
        - name: Cache Nimble
          if: runner.os == 'Linux' || runner.os == 'macOS'
          id: cache-nimble
          uses: actions/cache@v4
          with:
            path: ~/.nimble
            key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}

        - name: Setup Msys
          if: runner.os == 'Windows'
          uses: msys2/setup-msys2@v2
          with:
            update: true
            cache: true
            install: 'git base-devel p7zip mingw-w64-x86_64-toolchain'

        - name: Install Nim (Linux)
          if: runner.os == 'Linux' && inputs.os != 'freebsd'
          uses: jiro4989/setup-nim-action@v1
          with:
            nim-version: '2.2.6'
            repo-token: ${{ inputs.token }}

        - name: Install Nim (macOS)
          if: runner.os == 'macOS'
          run: |
            brew update
            brew install nim
          shell: bash

        - name: Install Nim (Windows / mini)
          if: runner.os == 'Windows' && inputs.mode == 'mini'
          run: |
            mkdir dist
            mkdir nim
            curl -L https://nim-lang.org/download/dlls.zip -o dist/dlls.zip
            curl -L https://nim-lang.org/download/nim-2.2.6_x64.zip -o dist/nim.zip
            7z x dist/dlls.zip -obin
            7z x dist/nim.zip -onim

            export PATH="${{ github.workspace }}/nim/nim-2.2.6/bin":$PATH

            cd arturo
            ./build.nims build --mode ${{ inputs.mode }} --log
            cd ..
            cp bin/*.dll /usr/bin
            cp arturo/bin/arturo.exe /usr/bin
          shell: msys2 {0}

        - name: Install Nim (Windows / full)
          if: runner.os == 'Windows' && inputs.mode == 'full'
          run: |
            pacman --noconfirm -S mingw-w64-x86_64-mpfr
            mkdir dist
            mkdir nim
            curl -L https://nim-lang.org/download/dlls.zip -o dist/dlls.zip
            curl -L https://arturo-lang.s3.amazonaws.com/extra-dlls.zip -o dist/extradlls.zip
            curl -L https://nim-lang.org/download/nim-2.2.6_x64.zip -o dist/nim.zip
            7z x dist/dlls.zip -obin
            7z x dist/extradlls.zip -obin
            7z x dist/nim.zip -onim
            cp arturo/src/extras/webview/deps/dlls/x64/*.dll bin

            export PATH="${{ github.workspace }}/nim/nim-2.2.6/bin":$PATH

            cd arturo
            ./build.nims build --mode ${{ inputs.mode }} --log
            cd ..
            cp bin/*.dll /usr/bin
            cp arturo/bin/arturo.exe /usr/bin
            curl -L https://curl.se/ca/cacert.pem -o /usr/bin/cacert.pem
            
          shell: msys2 {0}

        - name: Install dependencies (Linux)
          if: runner.os == 'Linux' && inputs.os != 'freebsd'
          run: |
            sudo apt-get update
            sudo apt-get install libpcre3
          shell: bash

        - name: Install dependencies (Linux / mini / x86)
          if: runner.os == 'Linux' && inputs.os != 'freebsd' && inputs.mode == 'mini' && inputs.arch == 'x86'
          run: |
            sudo apt-get install gcc-multilib g++-multilib
          shell: bash

        - name: Install dependencies (Linux / mini / arm)
          if: runner.os == 'Linux' && inputs.os != 'freebsd' && inputs.mode == 'mini' && (inputs.arch == 'arm' || inputs.arch == 'arm64')
          run: |
            sudo apt-get install gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
          shell: bash

        - name: Install dependencies (Linux / full)
          if: runner.os == 'Linux' && inputs.os != 'freebsd' && inputs.mode != 'mini'
          run: |
            npm install -g uglify-js
            sudo apt-get install libgtk-3-dev libmpfr-dev
            UBUNTU_VERSION=$(lsb_release -rs)
            if [[ "$UBUNTU_VERSION" < "24.04" ]]; then
              sudo apt-get install -y libwebkit2gtk-4.0-dev
            else
              sudo apt-get install -y libwebkit2gtk-4.1-dev
            fi
          shell: bash

        - name: Install dependencies (macOS / arm)
          if: runner.os == 'macOS' && runner.arch == 'ARM64' && inputs.mode != 'mini'
          run: |
            brew install pcre
          shell: bash
        
        - name: Compile Arturo (Linux/macOS - amd64)
          if: inputs.os != 'freebsd' && inputs.os != 'web' &&  runner.os != 'Windows' && inputs.arch == 'amd64' && runner.arch != 'ARM64'
          run: |
            cd arturo
            ./build.nims --install --mode ${{inputs.mode}} --arch amd64 --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

        - name: Compile Arturo (macOS - M1)
          if: inputs.os != 'freebsd' && inputs.os != 'web' && inputs.arch == 'arm64' &&  (runner.os == 'macOS' && runner.arch == 'ARM64')
          run: |
            cd arturo
            ./build.nims --install --mode ${{inputs.mode}} --arch arm64 --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

        - name: Compile Arturo (Linux)
          if: inputs.os != 'freebsd' && inputs.os != 'web' && inputs.arch != 'amd64' && runner.os == 'Linux'
          run: |
            cd arturo
            ./build.nims --install --mode ${{inputs.mode}} --arch ${{inputs.arch}} --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

        - name: Compile Arturo (Web)
          if: inputs.os == 'web'
          run: |
            cd arturo
            ./build.nims --mode web --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

        - name: Build Arturo (FreeBSD / mini)
          if: inputs.os == 'freebsd' && inputs.mode == 'mini'
          uses: vmactions/freebsd-vm@v1
          with:
            usesh: true
            prepare: |
              pkg update
              pkg install -y wget nim bash
            run: |
              export PATH="/usr/local/nim/bin/:$PATH"
              ./build.nims --install --mode ${{ inputs.mode }} --log
              export PATH="$HOME/.arturo/bin:$PATH"

        - name: Build Arturo (FreeBSD / full)
          if: inputs.os == 'freebsd' && inputs.mode == 'full'
          uses: vmactions/freebsd-vm@v1
          with:
            usesh: true
            prepare: |
              pkg update
              pkg install -y wget nim bash pkgconf
              pkg install -y gtk3 mpfr openssl webkit2-gtk_${{ inputs.webkit }}
            run: |
              export PATH="/usr/local/nim/bin/:$PATH"
              ./build.nims --install --mode ${{ inputs.mode }} --log
              export PATH="$HOME/.arturo/bin:$PATH"