name: 'Arturo Builder'
description: 'Setup Arturo environment'
branding:
    icon: terminal
    color: purple
inputs:
    mode:
        description: >-
            The Arturo version to install
            (one of: 'mini', 'full', 'docgen', 'safe')
        default: 'full'
    token:
        description: >-
            The GITHUB_TOKEN secret.
        required: true
    arch:
        description: >-
            The architecture to build for.
            (one of: 'x86', 'arm', 'arm64', 'amd64')
        default: 'amd64'
    src:
        description: >-
            Which Arturo version to use.
        default: ''
    metadata:
        description: >-
            Embeddable build metadata
        default: ''
    os:
        description: >-
            Target operating system
            (one of: 'linux', 'windows', 'macos', 'freebsd', 'web')
        default: 'linux'
    webkit:
        description: >-
            WebKit version for Linux/FreeBSD full builds (one of: '40', '41')
        default: '41'
runs:
    using: "composite"
    steps:
        - name: Sanitize inputs and auto-detect platform
          id: v
          run: |
            # Auto-detect OS if not specified or is default 'linux'
            if [ "${{ inputs.os }}" = "" ] || [ "${{ inputs.os }}" = "linux" ]; then
                case "${{ runner.os }}" in
                    Linux)   detected_os="linux" ;;
                    macOS)   detected_os="macos" ;;
                    Windows) detected_os="windows" ;;
                    *)       detected_os="linux" ;;
                esac
            else
                detected_os="${{ inputs.os }}"
            fi

            # Auto-detect arch if not specified or is default 'amd64'
            if [ "${{ inputs.arch }}" = "" ] || [ "${{ inputs.arch }}" = "amd64" ]; then
                case "${{ runner.arch }}" in
                    ARM64) detected_arch="arm64" ;;
                    X64)   detected_arch="amd64" ;;
                    *)     detected_arch="amd64" ;;
                esac
            else
                detected_arch="${{ inputs.arch }}"
            fi

            # Auto-detect webkit version based on Ubuntu version if not specified
            if [ "${{ inputs.webkit }}" = "" ] || [ "${{ inputs.webkit }}" = "41" ]; then
                if [ "${{ runner.os }}" = "Linux" ]; then
                    UBUNTU_VERSION=$(lsb_release -rs 2>/dev/null || echo "24.04")
                    if [[ "$UBUNTU_VERSION" < "24.04" ]]; then
                        detected_webkit="40"
                    else
                        detected_webkit="41"
                    fi
                else
                    detected_webkit="41"
                fi
            else
                detected_webkit="${{ inputs.webkit }}"
            fi

            echo "os=$detected_os" >> $GITHUB_OUTPUT
            echo "arch=$detected_arch" >> $GITHUB_OUTPUT
            echo "mode=${{ inputs.mode != '' && inputs.mode || 'full' }}" >> $GITHUB_OUTPUT
            echo "webkit=$detected_webkit" >> $GITHUB_OUTPUT
            echo "src=${{ inputs.src }}" >> $GITHUB_OUTPUT
            echo "metadata=${{ inputs.metadata }}" >> $GITHUB_OUTPUT
          shell: bash

        - name: Debug build configuration
          run: |
            echo "======================================"
            echo "Arturo Builder Configuration"
            echo "======================================"
            echo "Runner OS:        ${{ runner.os }}"
            echo "Runner Arch:      ${{ runner.arch }}"
            echo "======================================"
            echo "Target OS:        ${{ steps.v.outputs.os }}"
            echo "Target Arch:      ${{ steps.v.outputs.arch }}"
            echo "Build Mode:       ${{ steps.v.outputs.mode }}"
            echo "WebKit Version:   ${{ steps.v.outputs.webkit }}"
            echo "Source Ref:       ${{ steps.v.outputs.src != '' && steps.v.outputs.src || '(latest)' }}"
            echo "Metadata:         ${{ steps.v.outputs.metadata != '' && steps.v.outputs.metadata || '(none)' }}"
            echo "======================================"
          shell: bash

        - name: Checkout Arturo repo
          if: steps.v.outputs.os != 'freebsd'
          uses: actions/checkout@v4
          with:
            repository: arturo-lang/arturo
            submodules: recursive
            path: arturo
            ref: ${{ steps.v.outputs.src }}

        - name: Set build metadata
          if: steps.v.outputs.os != 'freebsd' && steps.v.outputs.metadata != ''
          run: |
            echo "${{ steps.v.outputs.metadata }}" > arturo/version/metadata
          shell: bash

        - name: Cache ChooseNim
          if: runner.os == 'Linux' || runner.os == 'macOS'
          id: cache-choosenim
          uses: actions/cache@v4
          with:
            path: ~/.choosenim
            key: ${{ runner.os }}-choosenim-${{ steps.get-date.outputs.date }}
  
        - name: Cache Nimble
          if: runner.os == 'Linux' || runner.os == 'macOS'
          id: cache-nimble
          uses: actions/cache@v4
          with:
            path: ~/.nimble
            key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}

        - name: Setup Msys
          if: runner.os == 'Windows'
          uses: msys2/setup-msys2@v2
          with:
            update: true
            cache: true
            install: 'git base-devel p7zip mingw-w64-x86_64-toolchain'

        - name: Install Nim (Linux)
          if: runner.os == 'Linux' && steps.v.outputs.os != 'freebsd'
          uses: jiro4989/setup-nim-action@v2
          with:
            nim-version: '2.2.6'
            repo-token: ${{ inputs.token }}

        - name: Install Nim (macOS)
          if: runner.os == 'macOS'
          run: |
            brew update
            brew install nim
          shell: bash

        - name: Install Nim (Windows / mini)
          if: runner.os == 'Windows' && steps.v.outputs.mode == 'mini'
          run: |
            mkdir dist
            mkdir nim
            curl -L https://nim-lang.org/download/dlls.zip -o dist/dlls.zip
            curl -L https://nim-lang.org/download/nim-2.2.6_x64.zip -o dist/nim.zip
            7z x dist/dlls.zip -obin
            7z x dist/nim.zip -onim

            export PATH="${{ github.workspace }}/nim/nim-2.2.6/bin":$PATH

            cd arturo
            ./build.nims build --mode ${{ steps.v.outputs.mode }} --log
            cd ..
            cp bin/*.dll /usr/bin
            cp arturo/bin/arturo.exe /usr/bin
          shell: msys2 {0}

        - name: Install Nim (Windows / full)
          if: runner.os == 'Windows' && steps.v.outputs.mode == 'full'
          run: |
            pacman --noconfirm -S mingw-w64-x86_64-mpfr
            mkdir dist
            mkdir nim
            curl -L https://nim-lang.org/download/dlls.zip -o dist/dlls.zip
            curl -L https://arturo-lang.s3.amazonaws.com/extra-dlls.zip -o dist/extradlls.zip
            curl -L https://nim-lang.org/download/nim-2.2.6_x64.zip -o dist/nim.zip
            7z x dist/dlls.zip -obin
            7z x dist/extradlls.zip -obin
            7z x dist/nim.zip -onim
            cp arturo/src/extras/webview/deps/dlls/x64/*.dll bin

            export PATH="${{ github.workspace }}/nim/nim-2.2.6/bin":$PATH

            cd arturo
            ./build.nims build --mode ${{ steps.v.outputs.mode }} --log
            cd ..
            cp bin/*.dll /usr/bin
            cp arturo/bin/arturo.exe /usr/bin
            curl -L https://curl.se/ca/cacert.pem -o /usr/bin/cacert.pem
            
          shell: msys2 {0}

        - name: Install dependencies (Linux)
          if: runner.os == 'Linux' && steps.v.outputs.os != 'freebsd'
          run: |
            sudo apt-get update
            sudo apt-get install libpcre3
          shell: bash

        - name: Install dependencies (Linux / mini / x86)
          if: runner.os == 'Linux' && steps.v.outputs.os != 'freebsd' && steps.v.outputs.mode == 'mini' && steps.v.outputs.arch == 'x86'
          run: |
            sudo apt-get install gcc-multilib g++-multilib
          shell: bash

        - name: Install dependencies (Linux / mini / arm)
          if: runner.os == 'Linux' && steps.v.outputs.os != 'freebsd' && steps.v.outputs.mode == 'mini' && (steps.v.outputs.arch == 'arm' || steps.v.outputs.arch == 'arm64')
          run: |
            sudo apt-get install gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
          shell: bash

        - name: Install dependencies (Linux / full)
          if: runner.os == 'Linux' && steps.v.outputs.os != 'freebsd' && steps.v.outputs.mode != 'mini'
          run: |
            npm install -g uglify-js
            sudo apt-get install libgtk-3-dev libmpfr-dev
            UBUNTU_VERSION=$(lsb_release -rs)
            if [[ "$UBUNTU_VERSION" < "24.04" ]]; then
                sudo apt-get install -y libwebkit2gtk-4.0-dev
            else
                sudo apt-get install -y libwebkit2gtk-4.1-dev
            fi
          shell: bash

        - name: Install dependencies (macOS / arm)
          if: runner.os == 'macOS' && runner.arch == 'ARM64' && steps.v.outputs.mode != 'mini'
          run: |
            brew install pcre
          shell: bash
        
        - name: Compile Arturo (Linux/macOS - amd64)
          if: steps.v.outputs.os != 'freebsd' && steps.v.outputs.os != 'web' &&  runner.os != 'Windows' && steps.v.outputs.arch == 'amd64' && runner.arch != 'ARM64'
          run: |
            cd arturo
            ./build.nims --install --mode ${{ steps.v.outputs.mode }} --arch amd64 --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

        - name: Compile Arturo (macOS - M1)
          if: steps.v.outputs.os != 'freebsd' && steps.v.outputs.os != 'web' && steps.v.outputs.arch == 'arm64' &&  (runner.os == 'macOS' && runner.arch == 'ARM64')
          run: |
            cd arturo
            ./build.nims --install --mode ${{ steps.v.outputs.mode }} --arch arm64 --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

        - name: Compile Arturo (Linux)
          if: steps.v.outputs.os != 'freebsd' && steps.v.outputs.os != 'web' && steps.v.outputs.arch != 'amd64' && runner.os == 'Linux'
          run: |
            cd arturo
            ./build.nims --install --mode ${{ steps.v.outputs.mode }} --arch ${{ steps.v.outputs.arch }} --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

        - name: Compile Arturo (Web)
          if: steps.v.outputs.os == 'web'
          run: |
            cd arturo
            ./build.nims --mode web --log
            echo "$HOME/.arturo/bin" >> $GITHUB_PATH
            cd ..
          shell: bash

        - name: Build Arturo (FreeBSD / mini)
          if: steps.v.outputs.os == 'freebsd' && steps.v.outputs.mode == 'mini'
          uses: vmactions/freebsd-vm@v1
          with:
            usesh: true
            sync: sshfs
            prepare: |
              pkg update
              pkg install -y wget nim bash git
            run: |
              git clone --recursive https://github.com/arturo-lang/arturo.git arturo
              cd arturo
              git config --global --add safe.directory '*'
              ${{ steps.v.outputs.src != '' && format('git checkout {0}', steps.v.outputs.src) || '' }}
              ${{ steps.v.outputs.metadata != '' && format('echo "{0}" > version/metadata', steps.v.outputs.metadata) || '' }}
              export PATH="/usr/local/nim/bin/:$PATH"
              ./build.nims --install --mode ${{ steps.v.outputs.mode }} --log

        - name: Build Arturo (FreeBSD / full)
          if: steps.v.outputs.os == 'freebsd' && steps.v.outputs.mode == 'full'
          uses: vmactions/freebsd-vm@v1
          with:
            usesh: true
            sync: sshfs
            prepare: |
              pkg update
              pkg install -y wget nim bash git pkgconf
              pkg install -y gtk3 mpfr openssl webkit2-gtk_${{ steps.v.outputs.webkit }}
            run: |
              git clone --recursive https://github.com/arturo-lang/arturo.git arturo
              cd arturo
              git config --global --add safe.directory '*'
              ${{ steps.v.outputs.src != '' && format('git checkout {0}', steps.v.outputs.src) || '' }}
              ${{ steps.v.outputs.metadata != '' && format('echo "{0}" > version/metadata', steps.v.outputs.metadata) || '' }}
              export PATH="/usr/local/nim/bin/:$PATH"
              ./build.nims --install --mode ${{ steps.v.outputs.mode }} --log